[package]
name = "pingora-cache"
version = "0.8.0"
authors = ["Yuchen Wu <yuchen@cloudflare.com>"]
license = "Apache-2.0"
edition = "2021"
rust-version = "1.85"
repository = "https://github.com/cloudflare/pingora"
categories = ["asynchronous", "network-programming"]
keywords = ["async", "http", "cache"]
description = """
HTTP caching APIs for Pingora proxy.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pingora_cache"
path = "src/lib.rs"

[dependencies]
pingora-core = { workspace = true, default-features = false }
pingora-error = { workspace = true }
pingora-header-serde = { workspace = true }
pingora-http = { workspace = true }
pingora-lru = { workspace = true }
pingora-timeout = { workspace = true }
bstr = { workspace = true }
http = { workspace = true }
indexmap = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
blake2 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
rmp-serde = { workspace = true }
bytes = { workspace = true }
httpdate = { workspace = true }
log = { workspace = true }
async-trait = { workspace = true }
parking_lot = { workspace = true }
cf-rustracing = { workspace = true, optional = true }
cf-rustracing-jaeger = { workspace = true, optional = true }
rmp = { workspace = true }
tokio = { workspace = true }
lru = { workspace = true }
ahash = { workspace = true }
hex = { workspace = true }
httparse = { workspace = true }
strum = { workspace = true, features = ["derive"] }
rand = { workspace = true }
arrayvec = { workspace = true }

[dev-dependencies]
cf-rustracing = { workspace = true }
cf-rustracing-jaeger = { workspace = true }
tokio-test = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
env_logger = { workspace = true }
dhat = { workspace = true }
futures = { workspace = true }

[[bench]]
name = "simple_lru_memory"
harness = false

[[bench]]
name = "lru_memory"
harness = false

[[bench]]
name = "lru_serde"
harness = false

[features]
default = []
openssl = ["pingora-core/openssl"]
boringssl = ["pingora-core/boringssl"]
rustls = ["pingora-core/rustls"]
s2n = ["pingora-core/s2n"]
trace = ["dep:cf-rustracing", "dep:cf-rustracing-jaeger"]
