[package]
name = "pingora-openssl"
version = "0.8.0"
authors = ["Yuchen Wu <yuchen@cloudflare.com>"]
license = "Apache-2.0"
edition = "2021"
repository = "https://github.com/cloudflare/pingora"
categories = ["asynchronous", "network-programming"]
keywords = ["async", "tls", "ssl", "pingora"]
description = """
OpenSSL async APIs for Pingora.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pingora_openssl"
path = "src/lib.rs"

[dependencies]
openssl-sys = { workspace = true }
openssl = { workspace = true }
tokio-openssl = { workspace = true }
libc = { workspace = true }
foreign-types = { workspace = true }

[dev-dependencies]
tokio-test = { workspace = true }
tokio = { workspace = true, features = ["full"] }
