[package]
name = "pingora-s2n"
version = "0.8.0"
license = "Apache-2.0"
edition = "2021"
repository = "https://github.com/cloudflare/pingora"
categories = ["asynchronous", "network-programming"]
keywords = ["async", "tls", "ssl", "pingora"]
description = """
S2N async APIs for Pingora.
"""

[lib]
name = "pingora_s2n"
path = "src/lib.rs"

[dependencies]
pingora-error = { workspace = true }
ring = { workspace = true }
s2n-tls = { workspace = true }
s2n-tls-tokio = { workspace = true }
