[package]
name = "pingora-rustls"
version = "0.8.0"
license = "Apache-2.0"
edition = "2021"
repository = "https://github.com/cloudflare/pingora"
categories = ["asynchronous", "network-programming"]
keywords = ["async", "tls", "ssl", "pingora"]
description = """
RusTLS async APIs for Pingora.
"""

[lib]
name = "pingora_rustls"
path = "src/lib.rs"

[dependencies]
log = { workspace = true }
pingora-error = { workspace = true }
ring = { workspace = true }
rustls = { workspace = true, features = ["ring"] }
rustls-native-certs = { workspace = true }
rustls-pemfile = { workspace = true }
rustls-pki-types = { workspace = true }
tokio-rustls = { workspace = true }
no_debug = { workspace = true }
