[package]
name = "pingora-header-serde"
version = "0.8.0"
authors = ["Yuchen Wu <yuchen@cloudflare.com>"]
license = "Apache-2.0"
edition = "2021"
repository = "https://github.com/cloudflare/pingora"
categories = ["compression"]
keywords = ["http", "compression", "pingora"]
exclude = ["samples/*"]
description = """
HTTP header (de)serialization and compression for Pingora.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pingora_header_serde"
path = "src/lib.rs"

[[bin]]
name = "trainer"
path = "src/trainer.rs"

[dependencies]
zstd = { workspace = true }
zstd-safe = { workspace = true, features = ["std"] }
http = { workspace = true }
bytes = { workspace = true }
httparse = { workspace = true }
pingora-error = { workspace = true }
pingora-http = { workspace = true }
thread_local = { workspace = true }
